/*
--------------------------------------------------------------------
XXXX           PYTEMPLATE AUTOMATICALLY GENERATED FILE          XXXX

        version 0.01                                                
        Generated 2015-02-14 12:25:09.694000
        
XXXX    DO NOT EDIT THIS FILE                                   XXXX
--------------------------------------------------------------------
*/

/* This file defines the serial codes for 
android<->arduino communication. If you wish to 
edit this file, change serial_codes.ino.pytemplate
and re-run the pytemplate generator.

*/

#ifndef SERIAL_H
#define SERIAL_H


/* AUTO CODE BEGIN */

#define	SET_STATE           		0 // state 1 is playing, 0 is disabled, may add more
#define	SET_LIVES           		10 // changes current lives
#define	SET_SHIELD          		11 // sets current shield
#define	SET_RESPAWN         		12 // sets respawn time (displacement from current time in ms)
#define	SET_PID             		20 // sets this players id [0,254]
#define	SET_TID             		21 // sets this players team id [0,15]
#define	SET_GID             		22 // sets this players game id [0,254]
#define	SET_COLOR           		23 // sets this players color
#define	ADD_ENEMY           		28 // adds an enemy team for this player (can be hit by them)
#define	CLEAR_ENEMIES       		29 // clears all enemy teams
#define	SET_NUM_GUNS        		30 // sets the loadout size
#define	SET_GUN_0           		31 // sets loadout position 0
#define	SET_GUN_1           		32 // sets loadout position 1
#define	SET_GUN_2           		33 // sets loadout position 2
#define	SET_GUN_3           		34 // sets loadout position 3
#define	TRY_FIRE            		40 // Sent when the player pulls the trigger
#define	FIRE_SUCCESS        		41 // Sent telling android whether the gun fired or not
#define	TRY_RELOAD          		42 // Sent when the player pulls the reload trigger
#define	RELOAD_SUCCESS      		43 // Sent telling android whether the gun finished reloading
#define	SET_AMMO            		44 // Sets the current ammo of the current gun
#define	SET_ACTIVE          		45 // Sets the current gun [0,3]
#define	NO_LIVES            		46 // Sent when the player runs out of lives
#define	HIT_BY              		48 // Specifies who hit us and with what
#define	KILLED_BY           		49 // Specifies who killed us and with what
#define	SET_START_TIME      		50 // Sets the game start time as a displacement (ms) from the current time
#define	SET_END_TIME        		51 // Sets the game end time as a displacement (ms) from the current time
#define	END_GAME            		59 // Immediately stops the current game
#define	ACK                 		254 // simple acknowledgement
#define	FLUSH               		255 // sending this at any point will refresh the serial buffer

/* AUTO CODE END */

#endif
